export const REQUEST_BOOKSHELVES = 'REQUEST_BOOKSHELVES';
export const RECEIVE_BOOKSHELVES = 'RECEIVE_BOOKSHELVES';

export const REQUEST_BOOKS = 'REQUEST_BOOKS';
export const RECEIVE_BOOKS = 'RECEIVE_BOOKS';
